sudo: true
dist: trusty
language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
    - sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu trusty/'
    - sudo apt update
    - sudo apt-get -y install r-base
    - sudo su - -c "R -e \"install.packages('geosphere', repos = 'http://cran.rstudio.com/')\""

script:
    - make travis

after_success:
    - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then bash <(curl -s https://codecov.io/bash); fi

cache:
    directories:
        - $HOME/.composer/cache
